on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:  
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: "."  # Scan the entire repository
          quiet: false    # Optional: Show detailed output
          soft_fail: true 
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci
